import bcrypt from "bcryptjs";

const H = 36e5;
const D = 24 * H;
const ago = (d = 0, h = 0) => new Date(Date.now() - d * D - h * H).toISOString();
const ahead = (d = 0, h = 0) => new Date(Date.now() + d * D + h * H).toISOString();

// Deterministic bcrypt hash for "Password123!" with 10 salt rounds (matches Supabase database)
export const SEED_PASSWORD_HASH =
  "$2b$10$FLiVrw6fJ6VtXMQg2IYiZOtTdKBVsFmdksV9yqii2zGtzur0kSt5K";

export const SEED_USERS = [
  {
    id: "u-admin",
    name: "City Operations Admin",
    email: "admin@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "ADMIN",
    department: null,
  },
  {
    id: "u-alvarez",
    name: "M. Alvarez",
    email: "m.alvarez@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Sanitation",
  },
  {
    id: "u-chen",
    name: "S. Chen",
    email: "s.chen@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Sanitation",
  },
  {
    id: "u-okafor",
    name: "J. Okafor",
    email: "j.okafor@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Parks & Forestry",
  },
  {
    id: "u-novak",
    name: "L. Novak",
    email: "l.novak@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Parks & Forestry",
  },
  {
    id: "u-kapoor",
    name: "R. Kapoor",
    email: "r.kapoor@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Water Utility",
  },
  {
    id: "u-nguyen",
    name: "T. Nguyen",
    email: "t.nguyen@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Water Utility",
  },
  {
    id: "u-petrova",
    name: "D. Petrova",
    email: "d.petrova@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Public Works",
  },
  {
    id: "u-mensah",
    name: "A. Mensah",
    email: "a.mensah@greenwatch.gov",
    passwordHash: SEED_PASSWORD_HASH,
    role: "OFFICIAL",
    department: "Public Works",
  },
];

export const SEED_REPORTS = [
  {
    id: "r1",
    ref: "GW-2041",
    category: "garbage",
    description:
      "Six or seven garbage bags dumped behind the market dumpsters — third time this month. The smell is getting bad and the pile is starting to block the storm drain.",
    location: {
      address: "Market Court, behind Block C dumpsters",
      area: "Riverside District",
      lat: 40.7123,
      lng: -74.0021,
    },
    photos: ["/src/assets/garbage.jpg"],
    priority: "High",
    status: "In Progress",
    department: "Sanitation",
    assignee: "M. Alvarez",
    createdAt: ago(3, 4),
    updatedAt: ago(0, 6),
    dueDate: ago(0, 6),
    resolvedAt: null,
    workOrder: "WO-1187",
    ai: {
      severity: "High",
      reason: "Public health and environmental risk",
      evidence: "Good",
      confidence: 94,
      similar: { count: 2, ids: ["r8"] },
    },
    activity: [
      { kind: "agent", who: "Triage Agent", text: "Classified as Illegal Garbage Dumping (94% confidence).", at: ago(3, 4) },
      { kind: "agent", who: "Evidence Agent", text: "1 photo verified, matches the report. Evidence quality: Good.", at: ago(3, 3) },
      { kind: "agent", who: "Duplicate Detection", text: "2 similar reports found in this area. Linked, not merged.", at: ago(3, 3) },
      { kind: "agent", who: "Priority Agent", text: "Priority set to High — public health and environmental risk.", at: ago(3, 3) },
      { kind: "agent", who: "Routing Agent", text: "Routed to Sanitation. Work order WO-1187 created.", at: ago(3, 3) },
      { kind: "human", who: "M. Alvarez", text: "Crew scheduled for tomorrow morning.", at: ago(0, 20) },
      { kind: "agent", who: "Follow-up Agent", text: "Update requested from the Sanitation team — report is past its due date.", at: ago(0, 6) },
    ],
  },
  {
    id: "r2",
    ref: "GW-2040",
    category: "garbage",
    description:
      "Pile of construction debris and two old mattresses left on the walkway. It's been here since the weekend and people are adding to it.",
    location: {
      address: "Riverside Walkway, near Pier 3",
      area: "Riverside District",
      lat: 40.7089,
      lng: -74.0112,
    },
    photos: ["/src/assets/garbage.jpg"],
    priority: "Medium",
    status: "Verified",
    department: "Sanitation",
    assignee: null,
    createdAt: ago(1, 2),
    updatedAt: ago(1, 0),
    dueDate: ahead(2),
    resolvedAt: null,
    workOrder: "WO-1191",
    ai: {
      severity: "Medium",
      reason: "Waste accumulation in a busy public area",
      evidence: "Good",
      confidence: 91,
      similar: { count: 1, ids: ["r8"] },
    },
    activity: [
      { kind: "agent", who: "Triage Agent", text: "Classified as Illegal Garbage Dumping (91% confidence).", at: ago(1, 2) },
      { kind: "agent", who: "Evidence Agent", text: "Photo verified. Evidence quality: Good.", at: ago(1, 2) },
      { kind: "agent", who: "Priority Agent", text: "Priority set to Medium — no immediate safety risk.", at: ago(1, 2) },
      { kind: "agent", who: "Routing Agent", text: "Routed to Sanitation. Work order WO-1191 created, awaiting pickup.", at: ago(1, 2) },
    ],
  },
  {
    id: "r3",
    ref: "GW-2039",
    category: "tree",
    description:
      "A large branch split off the old elm and is hanging right over the school crossing. It creaks in the wind — could come down any time.",
    location: {
      address: "Elm Street, crossing near Bloom School",
      area: "Bloomfield",
      lat: 40.7212,
      lng: -73.9987,
    },
    photos: ["/src/assets/tree.jpg"],
    priority: "High",
    status: "Assigned",
    department: "Parks & Forestry",
    assignee: "J. Okafor",
    createdAt: ago(0, 22),
    updatedAt: ago(0, 4),
    dueDate: ahead(0, 14),
    resolvedAt: null,
    workOrder: "WO-1192",
    ai: {
      severity: "High",
      reason: "Safety hazard near a school crossing",
      evidence: "Good",
      confidence: 96,
      similar: { count: 0, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Triage Agent", text: "Classified as Fallen / Damaged Tree (96% confidence).", at: ago(0, 22) },
      { kind: "agent", who: "Priority Agent", text: "Priority set to High — safety hazard near a school crossing.", at: ago(0, 22) },
      { kind: "agent", who: "Routing Agent", text: "Routed to Parks & Forestry. Work order WO-1192 created.", at: ago(0, 22) },
      { kind: "human", who: "J. Okafor", text: "Arborist crew dispatched, will secure the crossing first.", at: ago(0, 4) },
    ],
  },
  {
    id: "r4",
    ref: "GW-2037",
    category: "water",
    description:
      "Water has been gushing out of the ground at the corner since last night. Running down the whole street — thousands of litres wasted.",
    location: {
      address: "Rosewood Lane & 5th Avenue",
      area: "Old Town",
      lat: 40.7156,
      lng: -73.9965,
    },
    photos: ["/src/assets/water.jpg"],
    priority: "High",
    status: "In Progress",
    department: "Water Utility",
    assignee: "R. Kapoor",
    createdAt: ago(2, 1),
    updatedAt: ago(0, 9),
    dueDate: ahead(1),
    resolvedAt: null,
    workOrder: "WO-1189",
    ai: {
      severity: "High",
      reason: "Active water loss — damage and waste risk",
      evidence: "Good",
      confidence: 95,
      similar: { count: 0, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Triage Agent", text: "Classified as Water Leakage / Wastage (95% confidence).", at: ago(2, 1) },
      { kind: "agent", who: "Priority Agent", text: "Priority set to High — active water loss.", at: ago(2, 1) },
      { kind: "agent", who: "Routing Agent", text: "Routed to Water Utility. Work order WO-1189 created.", at: ago(2, 1) },
      { kind: "human", who: "R. Kapoor", text: "Valve isolated on the north side. Excavation crew on site.", at: ago(0, 9) },
    ],
  },
  {
    id: "r5",
    ref: "GW-2036",
    category: "park",
    description:
      "The bins at the east playground are overflowing and there is litter all over the grass. Kids play right next to it.",
    location: {
      address: "Riverside Park, east playground",
      area: "Riverside District",
      lat: 40.7104,
      lng: -74.0098,
    },
    photos: [],
    priority: "Medium",
    status: "New",
    department: "Sanitation",
    assignee: null,
    createdAt: ago(0, 9),
    updatedAt: ago(0, 8),
    dueDate: ahead(3),
    resolvedAt: null,
    workOrder: "WO-1194",
    ai: {
      severity: "Medium",
      reason: "Hygiene concern in a children's play area",
      evidence: "Needs more info",
      confidence: 82,
      similar: { count: 1, ids: ["r11"] },
    },
    activity: [
      { kind: "agent", who: "Triage Agent", text: "Classified as Dirty Park (82% confidence).", at: ago(0, 9) },
      { kind: "agent", who: "Evidence Agent", text: "No photos attached — evidence quality: Needs more info.", at: ago(0, 8) },
      { kind: "agent", who: "Routing Agent", text: "Routed to Sanitation. Work order WO-1194 created.", at: ago(0, 8) },
    ],
  },
  {
    id: "r6",
    ref: "GW-2035",
    category: "blocked",
    description:
      "The side gate of the community garden has been chained shut for two weeks. Elderly residents used that entrance every morning.",
    location: {
      address: "Community Garden, Hill Road gate",
      area: "Hill District",
      lat: 40.7244,
      lng: -74.0041,
    },
    photos: ["/src/assets/blocked.jpg"],
    priority: "Medium",
    status: "New",
    department: "Public Works",
    assignee: null,
    createdAt: ago(0, 15),
    updatedAt: ago(0, 15),
    dueDate: ahead(4),
    resolvedAt: null,
    workOrder: "WO-1195",
    ai: {
      severity: "Medium",
      reason: "Public green space inaccessible to residents",
      evidence: "Needs more info",
      confidence: 78,
      similar: { count: 1, ids: ["r12"] },
    },
    activity: [
      { kind: "agent", who: "Triage Agent", text: "Classified as Blocked Green Area (78% confidence).", at: ago(0, 15) },
      { kind: "agent", who: "Routing Agent", text: "Routed to Public Works. Work order WO-1195 created.", at: ago(0, 15) },
    ],
  },
  {
    id: "r7",
    ref: "GW-2033",
    category: "plants",
    description:
      "The flower beds around the fountain are trampled flat. Needs replanting and maybe a low barrier so it doesn't happen again.",
    location: {
      address: "Central Plaza, fountain beds",
      area: "City Center",
      lat: 40.7178,
      lng: -74.0008,
    },
    photos: ["/src/assets/plants.jpg"],
    priority: "Low",
    status: "New",
    department: "Parks & Forestry",
    assignee: null,
    createdAt: ago(1, 5),
    updatedAt: ago(1, 5),
    dueDate: ahead(5),
    resolvedAt: null,
    workOrder: "WO-1196",
    ai: {
      severity: "Low",
      reason: "Cosmetic damage to maintained greenery",
      evidence: "Good",
      confidence: 86,
      similar: { count: 0, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Triage Agent", text: "Classified as Damaged Plants (86% confidence).", at: ago(1, 5) },
      { kind: "agent", who: "Routing Agent", text: "Routed to Parks & Forestry. Work order WO-1196 created.", at: ago(1, 5) },
    ],
  },
  {
    id: "r8",
    ref: "GW-2031",
    category: "garbage",
    description:
      "Cardboard boxes and food waste dumped in the rear alley behind the market. Blocking the delivery entrance.",
    location: {
      address: "Lakeside Market, rear alley",
      area: "Lakeside",
      lat: 40.7052,
      lng: -74.0154,
    },
    photos: ["/src/assets/garbage.jpg"],
    priority: "Medium",
    status: "Resolved",
    department: "Sanitation",
    assignee: "S. Chen",
    createdAt: ago(6),
    updatedAt: ago(0, 3),
    dueDate: ahead(2),
    resolvedAt: ago(0, 3),
    workOrder: "WO-1181",
    ai: {
      severity: "Medium",
      reason: "Waste accumulation in a busy public area",
      evidence: "Good",
      confidence: 92,
      similar: { count: 1, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Routing Agent", text: "Routed to Sanitation. Work order WO-1181 created.", at: ago(6) },
      { kind: "human", who: "S. Chen", text: "Alley cleared and washed. Anti-dumping sign requested.", at: ago(0, 5) },
      { kind: "human", who: "S. Chen", text: "Marked as Resolved.", at: ago(0, 3) },
      { kind: "agent", who: "Follow-up Agent", text: "Citizen notified and asked to confirm the fix.", at: ago(0, 3) },
    ],
  },
  {
    id: "r9",
    ref: "GW-2028",
    category: "water",
    description:
      "Sprinkler on the Willow Court verge runs all night — the timer seems stuck open. Water flows straight into the gutter.",
    location: {
      address: "Willow Court, green verge",
      area: "Willowbend",
      lat: 40.7013,
      lng: -73.9923,
    },
    photos: ["/src/assets/water.jpg"],
    priority: "Low",
    status: "Resolved",
    department: "Water Utility",
    assignee: "T. Nguyen",
    createdAt: ago(5),
    updatedAt: ago(0, 6),
    dueDate: ahead(1),
    resolvedAt: ago(0, 6),
    workOrder: "WO-1179",
    ai: {
      severity: "Low",
      reason: "Steady water waste, no damage risk",
      evidence: "Good",
      confidence: 89,
      similar: { count: 0, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Routing Agent", text: "Routed to Water Utility. Work order WO-1179 created.", at: ago(5) },
      { kind: "human", who: "T. Nguyen", text: "Timer valve replaced. Marked as Resolved.", at: ago(0, 6) },
      { kind: "agent", who: "Follow-up Agent", text: "Citizen notified. No re-report in 24h — loop closed.", at: ago(0, 5) },
    ],
  },
  {
    id: "r10",
    ref: "GW-2025",
    category: "tree",
    description:
      "Heavy cracked branch hanging over the bus stop roof. It creaks loudly in the wind and commuters are standing underneath it.",
    location: {
      address: "Bus stop 12, Northgate Avenue",
      area: "Northgate",
      lat: 40.7291,
      lng: -74.0069,
    },
    photos: ["/src/assets/tree.jpg"],
    priority: "Medium",
    status: "In Progress",
    department: "Parks & Forestry",
    assignee: "L. Novak",
    createdAt: ago(4),
    updatedAt: ago(2, 3),
    dueDate: ago(1),
    resolvedAt: null,
    workOrder: "WO-1176",
    ai: {
      severity: "Medium",
      reason: "Obstruction risk in a shared public space",
      evidence: "Good",
      confidence: 90,
      similar: { count: 0, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Routing Agent", text: "Routed to Parks & Forestry. Work order WO-1176 created.", at: ago(4) },
      { kind: "human", who: "L. Novak", text: "Inspected — needs a cherry picker, scheduled this week.", at: ago(2, 3) },
      { kind: "agent", who: "Follow-up Agent", text: "Escalated: no update for 48h and report is past due. Reminder sent to crew supervisor.", at: ago(0, 2) },
    ],
  },
  {
    id: "r11",
    ref: "GW-2022",
    category: "park",
    description:
      "Dog park bins haven't been emptied in days. Waste bags are piling up near the entrance and the smell reaches the footpath.",
    location: {
      address: "Northgate dog park, main gate",
      area: "Northgate",
      lat: 40.7302,
      lng: -74.0089,
    },
    photos: ["/src/assets/park.jpg"],
    priority: "High",
    status: "Resolved",
    department: "Sanitation",
    assignee: "M. Alvarez",
    createdAt: ago(7),
    updatedAt: ago(1, 2),
    dueDate: ago(5),
    resolvedAt: ago(1, 2),
    workOrder: "WO-1170",
    ai: {
      severity: "High",
      reason: "Public health concern at a busy park entrance",
      evidence: "Good",
      confidence: 93,
      similar: { count: 2, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Routing Agent", text: "Routed to Sanitation. Work order WO-1170 created.", at: ago(7) },
      { kind: "agent", who: "Follow-up Agent", text: "Update requested from the Sanitation team.", at: ago(3) },
      { kind: "human", who: "M. Alvarez", text: "Bins emptied, extra pickup scheduled twice a week. Marked as Resolved.", at: ago(1, 2) },
    ],
  },
  {
    id: "r12",
    ref: "GW-2019",
    category: "blocked",
    description:
      "Scaffolding from the facade works blocks the pocket park entrance, so the whole walkway is unusable.",
    location: {
      address: "Fern Pocket Park, north entrance",
      area: "Old Town",
      lat: 40.7143,
      lng: -73.9944,
    },
    photos: ["/src/assets/blocked.jpg"],
    priority: "Low",
    status: "Resolved",
    department: "Public Works",
    assignee: "D. Petrova",
    createdAt: ago(9),
    updatedAt: ago(4),
    dueDate: ago(4),
    resolvedAt: ago(4),
    workOrder: "WO-1162",
    ai: {
      severity: "Low",
      reason: "Temporary obstruction, alternate path available",
      evidence: "Good",
      confidence: 84,
      similar: { count: 0, ids: [] },
    },
    activity: [
      { kind: "agent", who: "Routing Agent", text: "Routed to Public Works. Work order WO-1162 created.", at: ago(9) },
      { kind: "human", who: "D. Petrova", text: "Contractor re-secured the walkway, entrance reopened. Marked as Resolved.", at: ago(4) },
    ],
  },
];
